Extend CBMC Viewer to work with RBMC
awslabs/aws-viewer-for-cbmc pull request #31
Opened 2021-04-07 23:36 UTC by markrtuttle

This pull request make three small changes required for viewer to work on the output of rbmc in addition to cbmc.

2021-04-08 00:15 UTC, feliperodri approved these changes
LGTM module a few comments/questions.

2021-04-08 00:15 UTC, feliperodri commented on compare-coverage.py
> +################################################################
I'd remove it, seems unnecessary,

2021-04-08 00:15 UTC, feliperodri commented on compare-coverage.py
> +            ['diff', '/tmp/coverage1.json', '/tmp/coverage2.json'],
What about [filecmp](https://docs.python.org/3/library/filecmp.html)?

2021-04-08 00:15 UTC, feliperodri commented on compare-coverage.py
> +                difference[key] = proc.stdout
What don't you call `dict_diff` here?

2021-04-08 00:15 UTC, feliperodri commented on compare-result.py
> +################################################################
I'd remove it. It seems unnecessary.

2021-04-08 01:51 UTC, danielsn requested changes
Nothing major. But a few suggestions.

2021-04-08 01:51 UTC, danielsn commented on cbmc_viewer/markup_summary.py
> +            'line_num': symbols.lookup(func_name).get("line") if symbols.lookup(func_name) else 0
are we guaranteed that `line` exists if `func_name` does?

2021-04-08 01:51 UTC, danielsn commented on compare-coverage.py
> +        with open('/tmp/coverage1.json', 'w') as out1:
Should we ask python for a true tempfile? Hardcoding the names will cause problems if we run more than one process at once.

2021-04-08 01:51 UTC, danielsn commented on compare-coverage.py
> +def dict_diff(dict1, dict2):
It was a little unclear what this function does - took me several reads to understand. A comment would be helpful.

2021-04-08 01:51 UTC, danielsn commented on compare-coverage.py
> +                ['diff', '/tmp/coverage1.json', '/tmp/coverage2.json'],
are we guaranteed this will be on all machines we want to run on?

2021-04-08 01:51 UTC, danielsn commented on compare-coverage.py
> +                               for key, value in sorted(difference.items())}
why not just make the map up front?

2021-04-08 01:51 UTC, danielsn commented on compare-coverage.py
> +def compare(coverage1, coverage2, full=False, verbose=True):
Comment explaining what `full` means?

2021-04-08 01:51 UTC, danielsn commented on compare-coverage.py
> +def compare(coverage1, coverage2, full=False, verbose=True):
I believe verbose is not used?

2021-04-08 01:51 UTC, danielsn commented on compare-result.py
> +#!/usr/bin/env python3
Are we really not putting copyright headers on things?

2021-04-08 01:51 UTC, danielsn commented on compare-result.py
> +        JSON result output of make-result or cbmc-viewer.
what is `make-result`?

2021-04-08 01:51 UTC, danielsn commented on compare-result.py
> +    except KeyError:
Maybe this is pythonic, in which case keep doing it. But using exceptions for ordinary control flow seems weird to my non python native brain.

2021-05-18 18:53 UTC, markrtuttle commented on compare-coverage.py
> +################################################################
Done.

2021-05-18 19:11 UTC, markrtuttle commented on compare-result.py
> +################################################################
Done.

2021-05-18 23:13 UTC, markrtuttle commented
Closed in favor of #33

2021-05-18 23:13 UTC, closed without merging

2021-05-18 23:14 UTC, markrtuttle commented
The comparison scripts included in this pull request that generated the bulk of the discussion will be addressed in a separate pull request.